#!/bin/bash

set -e

extra_tags=()
extra_tags+=( "$DOCKER_REPO:python-$PYTHON37_VERSION-poetry-$POETRY_VERSION" )

for alias_tag in "${extra_tags[@]}"
do
    docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${alias_tag}"
    docker push "${DOCKER_REPO}:${alias_tag}"
done
